### ISSUE TITLE
Example of kernelspec to be used in K8S

### ISSUE THREAD

**Issue by echarles** [kevin-bates/remote_provisioners#3]
It would be great to have kernelspecs examples that work out-of-the-box on a local machine.

I am especially interested in the K8S deployement.

**Comment by kevin-bates** [comment]
As you can tell, this repo was constructed solely to house some of the code.  It is nowhere near ready for any kind of usage.  I will try to spend time here soon, but can't at the moment.

One of the things I'd like to help sort out (and could use some help frankly) is how to package remote provisioners since they all depend on a base remote provisioner.  I would prefer a single repository and am not familiar enough with python conventions to know how best that is accomplished or if it's conventional at all.

For example, the bracketed installation stuff looks interesting: `pip install remote-provisioners[k8s]` but is it possible to deploy only the k8s resources using that approach - or does that only apply to dependencies?

**Comment by echarles** [comment]
> As you can tell, this repo was constructed solely to house some of the code. It is nowhere near ready for any kind of usage. I will try to spend time here soon, but can't at the moment.

Thx Kevin for all the work you do on this front. Just wanted to know if the repo is usable. I can try it if you tell me I have reasonable chance to have it working :)

> For example, the bracketed installation stuff looks interesting: pip install remote-provisioners[k8s] but is it possible to deploy only the k8s resources using that approach - or does that only apply to dependencies?

Happy to help, but my approach would be first to have a toy working environment, and then optimize the packaging. I am not guru on that, but more hands can for sure help.

**Comment by kevin-bates** [comment]
The code in the remote-provisioners package _should_ work since I checked it in after confirming both YARN, Docker, and K8s.  However, deployment scripts and images are still EG-based so you'd need to extend the docker-stack notebook images to include my jupyter_client branch and the appropriate kernel-provisioner kernelspecs.  The EG kernel images, however, should be usable directly - so its really an exercise in converting the docker-stack image.

I'll try to make this a priority this week, although I've been really busy lately help on [elyra](https://github.com/elyra-ai/elyra) to get its 3.0 release out.

Here's a tar file that contains my tossed-together environment I used to test docker and k8s that might help get you going in the meantime: [raw-provisioning.zip](https://github.com/kevin-bates/remote_provisioners/files/6874103/raw-provisioning.zip)

**Comment by echarles** [comment]
> The code in the remote-provisioners package should work since I checked it in after confirming both YARN, Docker, and K8s. However, deployment scripts and images are still EG-based so you'd need to extend the docker-stack notebook images to include my jupyter_client branch and the appropriate kernel-provisioner kernelspecs. The EG kernel images, however, should be usable directly - so its really an exercise in converting the docker-stack image.

This is what I was expecting. Thx for confirming.

> I'll try to make this a priority this week, although I've been really busy lately help on elyra to get its 3.0 release out.

Super!  Have a good elyra release party!

> Here's a tar file that contains my tossed-together environment I used to test docker and k8s that might help get you going in the meantime: raw-provisioning.zip

Wonderful @kevin-bates as always. I will work on that artifact tomorrow and have good hope to make it work. Thx again!

**Comment by echarles** [comment]
I have done a few experiments. With the notebook running inside k8s if it worked fine (I had to give the needed k8s permission on the default service account). 

I have also tried to run the notebook outside of K8s. I remember this was not possible with the former kernel providers but wanted to give it a try again... I changed the config loading to not be "in_cluster" (so just config.load_kube_config() - with simple py code, I have access to my local minikube cluster). In that setting, the pod is launched and alive on the cluster, but on the server side (outside of the cluster), I hit a timeout

```
[W 2021-07-26 17:32:18.885 ServerApp] Nudge: attempt 20 on kernel cc991f61-916a-402f-a14f-2acc2f6a5891
```

For dev purposes, it would be great to be able to run the server outside, while having the kernels launched inside.

**Comment by kevin-bates** [comment]
Correct.  The k8s-provisioner requires that it be in the same network as the kernel pod.  This requirement alleviates the need to expose the zmq (and communication) ports of the kernel pod.  I think the use-case you're looking at (with the notebook/lab server outside the managed cluster) is one where either of the gateways would provide great value.  With provisioners, _Kernel_ Gateway essentially detaches the user's desktop from the managed clusters, just as Enterprise Gateway does prior to provisioning.  This way, only the JKG server port is exposed and is essentially static.

**Comment by echarles** [comment]
> Correct. The k8s-provisioner requires that it be in the same network as the kernel pod. This requirement alleviates the need to expose the zmq (and communication) ports of the kernel pod.

I understand that. If this use case makes sense, there would be 2 ways I'd like to invest thoughts and experiments:

1. Automating the creation a service and proxing/port-forwarding to that service. This could be done as part of dev utils scripts
2. Rely on existing kubernetes toolkit. I have seen a few around that promise better developer experience for the local vs cluster deployment, but I need to have an updated look at them.

>  I think the use-case you're looking at (with the notebook/lab server outside the managed cluster) is one where either of the gateways would provide great value. With provisioners, Kernel Gateway essentially detaches the user's desktop from the managed clusters, just as Enterprise Gateway does prior to provisioning. This way, only the JKG server port is exposed and is essentially static.

That sounds like a more sustainable and useful angle. Such a edge Gateway, running in the cluster and serving outside consumers, could benefit both the dev process, but also the real production cases.

Do you think EG is at a good place to be that Gateway, or do we need to start with something else?

**Comment by kevin-bates** [comment]
> Do you think EG is at a good place to be that Gateway, or do we need to start with something else?

Right now, EG is not because it's still using ProcessProxies - which, while essentially equivalent, are not compatible.  In fact, now that provisioners have been merged and slated for juptyer_client 7.0, I need to cap EG < 7.0.

The natural "edge Gateway" is Jupyter Kernel Gateway since it merely leverages the default kernel management.  We may want to update JKG to be based on Jupyter Server at some point (especially if there are changes needed for parameterization).

I see JKG being the _single-user_ (simple/lightweight) solution here, while JEG being more of a _multi-user_/_enterprise_ solution.  The difference being that EG would have capabilities like HA/DR and the notion of authorization (.e.g., users are not presented kernelspecs they are not authorized to use), etc.  This implies that EG will need to drop its process proxies and basically house a KernelManager and MultiKernelManager subclasses and handlers that provide this kind of functionality.

This is all quite overwhelming so here's a breakdown of how I envision the ecosystem relative to the Gateways and Kernel Management.

1. Jupyter Client 7.0 is released with support for Kernel Provisioners
     1. Work begins on parameterization and targets 7.1
     2. Applications are updated to take advantage of parameterization - Lab, Jupyter Server, JKG, JEG
1. Jupyter Kernel Gateway publishes 2.6 release (if necessary)
    1. JKG 3.0 is updated to depend on Jupyter Server rather than Notebook
    1. Work begins on major release to leverage parameterization (may not require any work)
 1. Jupyter Enterprise Gateway publishes a 2.6 release and caps jupyter_client < 7.0.  (The current master branch already contains the next major release work so some branch shuffling will be required.)
     1. Next major release (3.0) should probably leverage provisioners, so EG would DROP process proxy implementations.
     2. Although basic HA/DR and authorization are already implemented, adjustments relative to provisioners will be likely.

I'm sure there's more here, but needed to get the basics listed somewhere.

**Comment by echarles** [comment]
Quick feedback: What would prevent adding authorization and HA to JKG, which would make step 3 not needed?

**Comment by kevin-bates** [comment]
> What would prevent adding authorization and HA to JKG, which would make step 3 not needed?

Sure it makes "step 3" unnecessary but, IMHO would be the wrong move for the ecosystem - which is already too complicated.  I really believe that we need to preserve "simple deployment" options and JKG would provide that path.  Yes, JEG will likely _default_ to the functionality JKG provides but can be configured for enterprises.  And yes, you might find enterprises choosing to use JKG because they want to deploy simple, per-user, solutions and don't want multiple users accessing a single JEG endpoint (with HA/DR or not).

Probably worth discussing further, but that's my two cents.

**Comment by echarles** [comment]
When I am in the shoes of the "user" rather than the "developer", I am confused with those 2 offerings. My 2-cents would be that one option would be easier for the user, and also easier to maintain.

Absolutely worth discussing.

**Comment by lresende** [comment]
> When I am in the shoes of the "user" rather than the "developer", I am confused with those 2 offerings. My 2-cents would be that one option would be easier for the user, and also easier to maintain.
> 
> Absolutely worth discussing.

I also believe two offerings are confusing, in particular, because we have merged the support for "local kernels" into JEG. 
I would archive JKG, and move forward with JEG. 
As for the HTTP personality, which is the only thing JKG supports that is not in JEG, I would make that a single/separate package based on the community request and help to maintain it.

**Comment by echarles** [comment]
> I also believe two offerings are confusing, in particular, because we have merged the support for "local kernels" into JEG.
I would archive JKG, and move forward with JEG.

+1 assuming the default setup for JEG is simple enough to get started without all bells-and-whistles.

> As for the HTTP personality, which is the only thing JKG supports that is not in JEG, I would make that a single/separate package based on the community request and help to maintain it.

Yes, HTTP personality is something I love and need.

**Comment by echarles** [comment]
> in particular, because we have merged the support for "local kernels" into JEG.

@lresende @kevin-bates I am reloading my EG tests, and intrigued by the "local kernels" into JEG. Can you point to docs/code for this?

**Comment by echarles** [comment]
Maybe you meant this ? https://jupyter-enterprise-gateway.readthedocs.io/en/latest/kernel-local.html

In that case, would having EG depend on the new jupyter_client with kernel provisionner be a way to already use the new provisioner feature with EG?

**Comment by kevin-bates** [comment]
Yes, EG has always been able to run local kernels - to have parity (with respect to the _websocket personality_) with JKG.

> In that case, would having EG depend on the new jupyter_client with kernel provisionner be a way to already use the new provisioner feature with EG?

While this is true for JKG - it will get provisioners for free - this is not true for Enterprise Gateway until the current process proxies are _detangled_ (and removed) from the `RemoteKernelManager` and `RemoteMappingKernelManager` that was necessary PRIOR to provisioners.  Kernel Provisioners eliminate the tangle - much like hair conditioner. :smile:

**Comment by echarles** [comment]
Nice, I begin better seeing the road ahead to move from current EG proxies to the provisioners. I may stop pulling my hair out in a short time, which is always good news :)

**Comment by kevin-bates** [comment]
Closing as a result of #8.  

Complete kernel specifications will not be provided OOTB but, instead, be built using the CLI tooling.  Here's an example of a Kubernetes-based python kernel.json using the default options.

```
$ jupyter-k8s-spec install                                    
[I 2022-09-02 10:22:31.944 K8sSpecApp] Installing kernel specification for 'Kubernetes Python'
[I 2022-09-02 10:22:32.123 K8sSpecApp] Installed kernelspec k8s_python in /usr/local/share/jupyter/kernels/k8s_python
```

Here's the directory listing...
```
$ ls -R /usr/local/share/jupyter/kernels/k8s_python
kernel.json    logo-64x64.png scripts

/usr/local/share/jupyter/kernels/k8s_python/scripts: 
kernel-pod.yaml.j2   launch_kubernetes.py
```
and here's the `kernel.json`
```
$ cat /usr/local/share/jupyter/kernels/k8s_python/kernel.json
{
  "argv": [
    "python",
    "/usr/local/share/jupyter/kernels/k8s_python/scripts/launch_kubernetes.py",
    "--kernel-id",
    "{kernel_id}",
    "--port-range",
    "{port_range}",
    "--response-address",
    "{response_address}",
    "--public-key",
    "{public_key}",
    "--kernel_class_name",
    "ipykernel.ipkernel.IPythonKernel"
  ],
  "env": {},
  "display_name": "Kubernetes Python",
  "language": "python",
  "interrupt_mode": "signal",
  "metadata": {
    "debugger": true,
    "kernel_provisioner": {
      "provisioner_name": "kubernetes-provisioner",
      "config": {
        "image_name": "elyra/kernel-py:dev",
        "launch_timeout": 30
      }
    }
  }
}
```

**Comment by echarles** [comment]
Thx @kevin-bates I will try to take a look.

**Comment by kevin-bates** [comment]
Thanks @echarles.  Just to manage expectations, I have yet to take these updated provisioner implementations for a spin and strongly recommend you wait until #13 is resolved (which I'll be working on this afternoon).
